<?php

namespace Blog\ModelBundle\Repository;

use Blog\ModelBundle\Entity\Author;
use Doctrine\ORM\EntityRepository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository
{
    /**
     * find the first author
     *
     * @return Author
     */
    public function findFirst()
    {
        return $this->getQueryBuilder()
            -> orderBy('author.id', 'asc')
            -> setMaxResults(1)
            -> getQuery()
            -> getSingleResult();
    }


    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    private function getQueryBuilder()
    {
        $em = $this->getEntityManager();
        return $em -> getRepository('ModelBundle:Author') -> createQueryBuilder('author');

    }
}
