<?php

namespace Blog\ModelBundle\Repository;

use Blog\ModelBundle\Entity\Post;
use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @param int $num how many post to fetch
     *
     * @return array
     */
    public function findLatest($num) : array
    {
        return $this->getQueryBuilder()
            -> orderBy('post.createdAt', 'desc')
            -> setMaxResults($num)
            -> getQuery()
            -> getResult();

    }

    /**
     * find the first post
     *
     * @return Post
     */
    public function findFirst()
    {
        return $this->getQueryBuilder()
            -> orderBy('post.id', 'asc')
            -> setMaxResults(1)
            -> getQuery()
            -> getSingleResult();
    }

    private function getQueryBuilder()
    {
        $em = $this->getEntityManager();
        return $em -> getRepository('ModelBundle:Post') -> createQueryBuilder('post');

    }
}
